org: saikhanbileg
app: linktree
service: linkTree
frameworkVersion: '3'
useDotenv: true

	
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRESIN: ${env:JWT_EXPIRESIN}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
