org: saikhanbileg
app: linktree
service: linkTree
frameworkVersion: '3'
useDotenv: true

	
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 20000
  environment:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRESIN: ${env:JWT_EXPIRESIN}

functions:
  hello:
    handler: src/functions/link.hello
    events:
      - httpApi:
          path: /
          method: get
  createLink: 
    handler: src/functions/link.createLink
    events:
      - httpApi:
          path: /create
          method: post
  getLink: 
    handler: src/functions/link.getLink
    events:
      - httpApi:
          path: /{name+}
          method: get
  userReq:
    handler: src/functions/user.userReq
    events:
      - httpApi:
          path: /register
          method: post
  userLogin: 
    handler: src/functions/user.userLogin
    events:
      - httpApi:
          path: /login
          method: post

